[tool.poetry]
name = "ImgRar" 
version = "1.0.1"  
description = "Images to Code & Code to Images (Short ones)" 
authors = ["Atharv Desai <atharvdesai2002@gmail.com>"] 

[tool.poetry.dependencies]
python = "^3.8"
